# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-09 23:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UTN_ExamsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_alumno', models.CharField(max_length=500)),
                ('apellido_alumno', models.CharField(max_length=500)),
                ('dni_alumno', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('corregido', models.BooleanField(default=False)),
                ('resultado', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('nota', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('activo', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('preguntas', models.ManyToManyField(blank=True, null=True, related_name='preguntas_examen', to='UTN_ExamsApp.Pregunta')),
            ],
        ),
        migrations.AddField(
            model_name='revision',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='revision',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UTN_ExamsApp.Examen'),
        ),
    ]
